name: Playwright Tests

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test tests/specs/checkoutPaypal.spec

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Playwright report
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy Playwright report
        uses: actions/deploy-pages@v4
